run:
  deadline: 2m

linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400