name: Fuzz Testing
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '33 23 * * *' # Run at 23:33 every day
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fuzz
        run: make fuzz
